
name: Hello World

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Building Something!

      - name: Hello from Docker
        run: docker run hello-world

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy something 
        run: echo Deploying something!
      
       
     
